### ISSUE TITLE
User Story 2: Add basic security standards using Helmet

### ISSUE THREAD

**Issue by Stace0x** [SchoolOfCode/bc17-w4d2-project-group-out-at-sea#2]
As Norman, a Lead Engineer at TrackIt I want to use best practice npm packages like Helmet with my APIs so that I can get a level of safety and security by default.

As Jenny, the CTO of TrackIt I lose sleep over the idea of things like data breaches because in some cases I would be legally accountable so I want all our services and applications to be as secure as possible.

As Joe, a fitness fanatic I want to know that all my data is secure because bad people having access to the type, time and location of my fitness activities is a scary idea - I wouldn’t want to use an app that doesn’t look after my data.

```[tasklist]
### Tasks
- [x] instal Node Helmet
- [x] add middle-ware instruction for helmet
- [ ] disable to viewing of “X-Powered-By: Express” in the bobdy
```

**Comment by Stace0x** [comment]
in postman view find the body's header
