### ISSUE TITLE
User Story 4: Implement functionality to POST a new activity

### ISSUE THREAD

**Issue by ab-stha** [SchoolOfCode/bc17-w4d2-project-group-out-at-sea#4]
```[tasklist]
### Tasks
- [x] Create new async function to push a new activity in to the array
- [x] Call this function on app.js when the client has requested to post a new activity
- [ ] The new activities should have a unique “id” (UUID)
- [ ] They should also have activity_submitted (time stamp - Date.now()),
```

```[tasklist]
### Tasks
```
